__author__ = 'dstuebe'

"""
Provides a dictionary of available US sms services by email. Prefix the host with the phone number to send...

For the phone number (123) 456-7890 on 3 River Wireless:
"3 River Wireless":"12345607890@sms.3rivers.net"
"""

sms_providers =\
{
"3 River Wireless":"@sms.3rivers.net",
"Advantage Communications":"@advantagepaging.com",
"AirVoice":"@mmode.com",
"Airtouch Pagers":"@airtouch.net",
"AllTel":"@message.alltel.com",
"Alltel PCS":"@message.alltel.com",
"Alltel":"@alltelmessage.com",
"Ameritech Paging":"@pageapi.com",
"Arch Pagers (PageNet)":"@archwireless.net",
"Bell South (Blackberry)":"@bellsouthtips.com",
"Bell South Mobility":"@blsdcs.net",
"Bell South":"@sms.bellsouth.com",
"Bluegrass Cellular":"@sms.bluecell.com",
"Boost Mobile":"@myboostmobile.com",
"Boost":"@myboostmobile.com",
"CallPlus":"@mmode.com",
"Carolina Mobile Communications":"@cmcpaging.com",
"Cellular One East Coast":"@phone.cellone.net",
"Cellular One PCS":"@paging.cellone-sf.com",
"Cellular One South West":"@swmsg.com",
"Cellular One West":"@mycellone.com",
"Cellular One":"@mobile.celloneusa.com",
"Cellular South":"@csouth1.com",
"Central Vermont Communications":"@cvcpaging.com",
"CenturyTel":"@messaging.centurytel.net",
"Cingular (GSM)":"@cingularme.com",
"Cingular (TDMA)":"@mmode.com",
"Cingular Wireless":"@mobile.mycingular.net",
"Cingular":"@cingularme.com",
"Communication Specialists":"@pageme.comspeco.net",
"Cook Paging":"@cookmail.com",
"Corr Wireless Communications":"@corrwireless.net",
"Dobson Communications Corporation":"@mobile.dobson.ne",
"Dobson-Alex Wireless / Dobson-Cellular One":"@mobile.cellularone.com",
"Edge Wireless":"@sms.edgewireless.com",
"GCS Paging":"@webpager.us",
"GTE":"@gte.pagegate.net",
"Galaxy Corporation":"@sendabeep.net",
"GrayLink / Porta-Phone":"@epage.porta-phone.com",
"Houston Cellular":"@text.houstoncellular.net",
"Inland Cellular Telephone":"@inlandlink.com",
"JSM Tele-Page":"@jsmtel.com",
"Lauttamus Communication":"@e-page.net",
"MCI Phone":"@mci.com",
"MCI":"@pagemci.com",
"Metro PCS":"@metropcs.sms.us",
"MetroPCS":"@mymetropcs.com",
"Metrocall 2-way":"@my2way.com",
"Metrocall":"@page.metrocall.com",
"Midwest Wireless":"@clearlydigital.com",
"Mobilecom PA":"@page.mobilcom.net",
"Mobilfone":"@page.mobilfone.com",
"Morris Wireless":"@beepone.net",
"NPI Wireless":"@npiwireless.com",
"Nextel":"@messaging.nextel.com",
"Ntelos":"@pcs.ntelos.com",
"Omnipoint":"@omnipoint.com",
"OnlineBeep":"@onlinebeep.net",
"PCS One":"@pcsone.net",
"Pacific Bell":"@pacbellpcs.net",
"PageMart":"@pagemart.net",
"PageOne NorthWest":"@page1nw.com",
"Pioneer / Enid Cellular":"@msg.pioneerenidcellular.com",
"Price Communications":"@mobilecell1se.com",
"ProPage":"@page.propage.net",
"Public Service Cellular":"@sms.pscel.com",
"Qualcomm":"@pager.qualcomm.com",
"Qwest":"@qwestmp.com",
"RAM Page":"@ram-page.com",
"ST Paging":"@page.stpaging.com",
"Safaricom":"@safaricomsms.com",
"Satelindo GSM":"@satelindogsm.com",
"Satellink":".pageme@satellink.net",
"Simple Freedom":"@text.simplefreedom.net",
"Skytel Pagers":"@skytel.com",
"Smart Telecom":"@mysmart.mymobile.ph",
"Southern LINC":"@page.southernlinc.com",
"Southwestern Bell":"@email.swbw.com",
"Sprint PCS":"@messaging.sprintpcs.com",
"Sprint":"@sprintpaging.com",
"SunCom":"@tms.suncom.com",
"Surewest Communications":"@mobile.surewest.com",
"T-Mobile":"@tmomail.net",
"TIM":"@timnet.com",
"TSR Wireless":"@beep.com",
"Teletouch":"@pageme.teletouch.com",
"Telus":"@msg.telus.com",
"The Indiana Paging Co":"@pager.tdspager.com",
"Triton":"@tms.suncom.com",
"US Cellular":"@email.uscc.net",
"USA Mobility":"@mobilecomm.net",
"Unicel":"@utext.com",
"Verizon PCS":"@myvzw.com",
"Verizon Pagers":"@myairmail.com",
"Verizon":"@vtext.com",
"Virgin Mobile":"@vmobl.com",
"WebLink Wireless":"@pagemart.net",
"West Central Wireless":"@sms.wcc.net",
"Western Wireless":"@cellularonewest.com",
"Wyndtell":"@wyndtell.com",
}