#!/usr/bin/env python

"""
@package ion.agents.platform.platform_driver
@file    ion/agents/platform/platform_driver.py
@author  Carlos Rueda
@brief   Base class for platform drivers
         PRELIMINARY
"""

__author__ = 'Carlos Rueda'
__license__ = 'Apache 2.0'


from pyon.public import log

import time


class DriverEvent(object):
    """
    Base class for driver events.
    """
    def __init__(self, value, ts):
        self._value = value
        self._ts = ts


class AttributeValueDriverEvent(DriverEvent):
    """
    Event to notify the retrieved value for a platform attribute.
    """
    def __init__(self, platform_id, attr_id, value, ts):
        DriverEvent.__init__(self, value, ts)
        self._platform_id = platform_id
        self._attr_id = attr_id


class PlatformDriver(object):
    """
    A platform driver handles a particular platform in a platform network.
    """

    def __init__(self, platform_id):

        self._platform_id = platform_id
        self._send_event = None

        # the root NNode defining the platform network rooted at the platform
        # identified by self._platform_id
        self._nnode = None

    def set_event_listener(self, evt_recv):
        """
        (to support similar setting in instrument-agent:
          driver_client.start_messaging(self.evt_recv)
        )
        Sets the listener of events generated by this driver.
        """
        self._send_event = evt_recv

    def go_active(self):
        """
        To be implemented by subclass.
        Establish communication with external platform and assigns self._nnode.
        """
        raise NotImplemented()

    def get_subplatform_ids(self):
        """
        Gets the IDs of the subplatforms of this driver's associated
        platform. This is based on self._nnode, which should have been
        assigned by a call to go_active.
        """
        assert self._nnode is not None, "go_active should have been called first"
        return self._nnode.subplatforms.keys()

    def start_resource_monitoring(self):
        """
        To be implemented by subclass.
        Starts greenlets to periodically retrieve values of the attributes
        associated with my platform, and do corresponding event notifications.
        """
        raise NotImplemented()

    def stop_resource_monitoring(self):
        """
        To be implemented by subclass.
        Stops all the monitoring greenlets.
        """
        raise NotImplemented()

    def destroy(self):
        """
        Stops all activity done by the driver. In this base class,
        this method calls self.stop_resource_monitoring()
        """
        self.stop_resource_monitoring()

    def _notify_driver_event(self, driver_event):
        """
        Convenience method for subclasses to send a driver event to
        corresponding platform agent.

        @param driver_event a DriverEvent object.
        """
        log.info("platform driver=%r: notify driver_event=%s" % (
            self._platform_id, driver_event))

        assert isinstance(driver_event, DriverEvent)

        if self._send_event:
            self._send_event(driver_event)
        else:
            log.warn("self._send_event not set to notify driver_event=%s" %
                     str(driver_event))
