#!/usr/bin/env python

"""
NOT USED because not really necessary for the current state of development and,
most importantly, because of Pyon-related misbehaviors. When Pyon stuff is
imported in some way, the following behaviors were observed at some point:

    - threads not started: likely caused by a mix of gevent
      monkey-patching (see test_thread.py for some details).

    - log messages not generated: log messages from test files are not
      generated when PyonTestCase (from pyon.util.unit_test) is used,
      and in combination with the TrhphTestCase used as a mixin. This was
      initially noted with test_driver_proc.py

"""

__author__ = 'Carlos Rueda'
__license__ = 'Apache 2.0'

#from pyon.util.unit_test import PyonTestCase
#from ion.services.mi.drivers.uw_trhph.test import TrhphTestCase
#
#
#class PyonTrhphTestCase(PyonTestCase, TrhphTestCase):
#    """
#    PyonTestCase base class for TRHPH test cases.
#
#    Note related with logging: it has been observed that log messages are not
#    generated by test cases derived from this class.
#    """
#
#    def setUp(self):
#        PyonTestCase.setUp(self)
#        TrhphTestCase.setUp(self)
#
#    def tearDown(self):
#        TrhphTestCase.tearDown(self)
#        PyonTestCase.tearDown(self)
