#!/usr/bin/env python

__author__ = 'Carlos Rueda'
__license__ = 'Apache 2.0'

from pyon.util.unit_test import PyonTestCase
from ion.services.mi.drivers.uw_bars.test import BarsTestCase


class PyonBarsTestCase(PyonTestCase, BarsTestCase):
    """
    PyonTestCase base class for BARS test cases.

    Note related with logging: it has been observed that log messages are not
    generated by test cases derived from this class.
    """

    def setUp(self):
        PyonTestCase.setUp(self)
        BarsTestCase.setUp(self)

    def tearDown(self):
        BarsTestCase.tearDown(self)
        PyonTestCase.tearDown(self)
